CREATE TABLE tbl_user(
   USERNAME VARCHAR(20) PRIMARY KEY NOT NULL,
   PASSWORD VARCHAR(20) NOT NULL,
   TIME_OF_CREATION TIMESTAMP NOT NULL
);

CREATE TABLE tbl_job(
	JOB_ID UUID PRIMARY KEY,
    TITLE VARCHAR(30) NOT NULL,
	EMPLOYER VARCHAR(20) REFERENCES tbl_user(USERNAME) on delete cascade,
	DESCRIPTION TEXT NOT NULL,
	THE_GEOM GEOMETRY NOT NULL,
	TIME_OF_CREATION TIMESTAMP NOT NULL,
	ASSIGNED_TO VARCHAR(20) REFERENCES tbl_user(USERNAME),
	ASSIGNED_AT TIMESTAMP
);

CREATE TABLE tbl_bid(
	BID_ID UUID PRIMARY KEY,
	JOB_ID UUID REFERENCES tbl_job(JOB_ID) on delete cascade,
	EMPLOYEE VARCHAR(20) REFERENCES tbl_user(USERNAME) on delete cascade,
	MESSAGE TEXT NOT NULL,
	TIME_OF_CREATION TIMESTAMP NOT NULL
);